#!/usr/bin/env tsx

/**
 * Hash Verification Script
 * 
 * This script verifies that multiple bcrypt hashes of the same password
 * all verify correctly, demonstrating that bcrypt's random salt doesn't
 * prevent verification.
 */

import { verifyPassword } from '../src/lib/users.js'

async function verifyHashes() {
  const password = 'admin'
  
  // The hash from the README
  const readmeHash = '$2b$10$i0/B9njRJ5DT7dl34pPDNuakaKKCE8sXZ7dmbwPuDuc7j3ylHgSoq'
  
  // Three different hashes generated by the script
  const hash1 = '$2b$10$Ow9Yel.k9UdatSSulyWI4uWxf.oRJq9IROxr7P9os.5TC.Qp1pCwa'
  const hash2 = '$2b$10$ixne0IgTiCfGDVDEI3Pin.U0DbtuEk4C0AGapvggkAYVLl3u.jqoi'
  const hash3 = '$2b$10$mv/B1epGmRsD3WrXan6kBerKvOXaV9Xz.iFGks3c99mq51LLBkdXq'
  
  console.log('==========================================')
  console.log('Hash Verification Test')
  console.log('==========================================')
  console.log(`Password being verified: "${password}"\n`)
  
  const readmeResult = await verifyPassword(password, readmeHash)
  console.log(`README hash:  ${readmeResult ? '✓ VALID' : '✗ INVALID'}`)
  
  const result1 = await verifyPassword(password, hash1)
  console.log(`Hash 1:       ${result1 ? '✓ VALID' : '✗ INVALID'}`)
  
  const result2 = await verifyPassword(password, hash2)
  console.log(`Hash 2:       ${result2 ? '✓ VALID' : '✗ INVALID'}`)
  
  const result3 = await verifyPassword(password, hash3)
  console.log(`Hash 3:       ${result3 ? '✓ VALID' : '✗ INVALID'}`)
  
  console.log('\n==========================================')
  
  // Check if all verifications passed
  const allValid = readmeResult && result1 && result2 && result3
  
  if (allValid) {
    console.log('All different hashes verify correctly!')
    console.log('==========================================')
    process.exit(0)
  } else {
    console.log('ERROR: Some hashes failed to verify!')
    console.log('==========================================')
    process.exit(1)
  }
}

verifyHashes().catch((error) => {
  console.error('Error verifying hashes:', error)
  process.exit(1)
})
